#1 Sprint 8
ufo1og/java-filmorate pull request #2
Opened 2022-06-29 05:29 UTC by ufo1og

2022-06-30 17:07 UTC, kukolev requested changes

2022-06-30 17:07 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +	public static void main(String[] args) {
Нарушение кодстайла: Лишние отступы слева перед кодом. Советую в IDEA просто нажать комбинацию клавиш  Ctrl + Alt + L и код автоматически отформатируется.

2022-06-30 17:07 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	@Test
Нарушение кодстайла: Лишние отступы слева перед кодом. Советую в IDEA просто нажать комбинацию клавиш  Ctrl + Alt + L и код автоматически отформатируется.

2022-06-30 17:07 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    ObjectMapper objectMapper;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-06-30 17:07 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +    ObjectMapper objectMapper;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-07-01 04:47 UTC, ufo1og commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +	public static void main(String[] args) {
У меня в idea там нет лишних отступов, сочетание клавиш ничего не изменило.
![image](https://user-images.githubusercontent.com/100068809/176825314-8a75f62b-12b8-4110-9f4e-2ed4dd0c6f4c.png)

2022-07-01 04:48 UTC, ufo1og commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	@Test
Аналогично с предыдущим замечанием

2022-07-01 04:48 UTC, ufo1og commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    ObjectMapper objectMapper;
Исправлено

2022-07-01 04:48 UTC, ufo1og commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +    ObjectMapper objectMapper;
Исправлено

2022-07-01 07:25 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +	public static void main(String[] args) {
Отступ в коде выполнен с помощью Tab, а по кодстайлу нужно делать четыре пробела. Это нарушение кодстайла, исправьте, пожалуйста.

2022-07-01 07:25 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +    ObjectMapper objectMapper;
Отступ в коде выполнен с помощью Tab, а по кодстайлу нужно делать четыре пробела. Это нарушение кодстайла, исправьте, пожалуйста.

2022-07-01 08:02 UTC, ufo1og commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +    ObjectMapper objectMapper;
А, теперь понял в чем дело.

2022-07-01 16:35 UTC, kukolev approved these changes

2022-07-01 17:54 UTC, merged