# Sprint 9
ufo1og/java-filmorate pull request #3
Opened 2022-07-14 11:43 UTC by ufo1og

2022-07-17 07:11 UTC, kukolev requested changes

2022-07-17 07:11 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +public class FilmService extends AbstractCommonService<Film, FilmStorage> {
Логику сервисов лучше покрыть логами. Так будет проще анализировать поведение программы, если что-то пойдет не так.

2022-07-17 07:11 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +public class UserService extends AbstractCommonService<User, UserStorage> {
Логику сервисов лучше покрыть логами. Так будет проще анализировать поведение программы, если что-то пойдет не так.

2022-07-17 09:14 UTC, ufo1og commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +public class FilmService extends AbstractCommonService<Film, FilmStorage> {
Добавил логирование в методы, где происходит создание, изменение или удаление сущностей.

2022-07-17 09:14 UTC, ufo1og commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +public class UserService extends AbstractCommonService<User, UserStorage> {
Добавил логирование в методы, где происходит создание, изменение или удаление сущностей.

2022-07-17 12:32 UTC, kukolev requested changes

2022-07-17 12:32 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/AbstractCommonService.java
> +            log.debug("Entity with id = " + id + " not found.");
При логировании лучше использовать возможности библиотеки и пользоваться плейсхолдерами `{}` вместо конкатенации строк. Лучше так: `log.warn("Some warning text for {}", val)` вместо `log.warn("Some warning text for " + val)`. Так код смотрится проще и не происходит лишняя конкатенация строк, если лог не будет напечатан.

2022-07-17 20:09 UTC, ufo1og commented on src/main/java/ru/yandex/practicum/filmorate/service/AbstractCommonService.java
> +            log.debug("Entity with id = " + id + " not found.");
Поправил.

2022-07-18 07:48 UTC, kukolev approved these changes

2022-07-18 15:19 UTC, merged