Add database
ufo1og/java-filmorate pull request #5
Opened 2022-08-11 05:20 UTC by ufo1og

# 11 Спринт

2022-08-11 15:44 UTC, kukolev requested changes

2022-08-11 15:44 UTC, kukolev commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:h2:file:./db/filmorate
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-08-11 15:44 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/storage/FilmDbStorageTest.java
> +    public void testCreateGetUpdateAndDeleteFilm() {
Тесты лучше разбивать на несколько, а не делать один универсальный тест. Если тестов несколько, то проще будет понять что именно пошло не так, когда один из тестов упадет.

2022-08-11 15:44 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/storage/UserDbStorageTest.java
> +    public void testCreateGetUpdateAndDeleteUser() {
Тесты лучше разбивать на несколько, а не делать один универсальный тест. Если тестов несколько, то проще будет понять что именно пошло не так, когда один из тестов упадет.

2022-08-11 15:44 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/FriendsDbStorage.java
> +                " WHERE user_from = ?1"; // AND status_id = 1
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-08-11 15:44 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/FriendsDbStorage.java
> +                " WHERE user_from IN (?1, ?2))" + //  AND status_id = 1
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-08-12 04:21 UTC, ufo1og commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:h2:file:./db/filmorate
Удалил закомментированную строку.

2022-08-12 04:50 UTC, ufo1og commented on src/test/java/ru/yandex/practicum/filmorate/storage/FilmDbStorageTest.java
> +    public void testCreateGetUpdateAndDeleteFilm() {
Разбил на 4 теста.

2022-08-12 04:51 UTC, ufo1og commented on src/test/java/ru/yandex/practicum/filmorate/storage/UserDbStorageTest.java
> +    public void testCreateGetUpdateAndDeleteUser() {
Разбил на 4 теста.

2022-08-12 07:30 UTC, kukolev approved these changes

2022-08-12 07:36 UTC, merged